# Generated by Django 3.2.3 on 2021-05-28 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=128)),
                ('inputfile', models.CharField(max_length=256)),
                ('parameters', models.TextField()),
            ],
        ),
    ]
