name : snapms
channels :
  - conda-forge
dependencies :
  - python==3.9
  - pip==21.1.1
  - rdkit==2021.03.2
  - numpy==1.20
  - pandas==1.2
  - networkx==2.5
  - scipy==1.6
  - pip:
    - py2cytoscape==0.7
    - python-dotenv==0.17
    - django==1.8
    - django-rq==2.4